### ISSUE TITLE
Installation CentOS

### ISSUE THREAD

**Issue by damanic** [arnaud-lb/php-memory-profiler#12]
Getting an error on install `sudo pecl install memprof`

```
checking for judy lib... yes, shared
checking for judy files in default path... not found
configure: error: Please reinstall the judy distribution
ERROR: `/var/tmp/memprof/configure' failed
```

I have tried
`yum install Judy`
but it makes no difference.

**Comment by knifesk** [comment]
You didn't specified the centos version.. but I had the same problem with remi repos for PHP 5.6 and Centos 6.5

I solved that running.. 
```
 yum install php56-build php-pecl-judy.x86_64 Judy-devel.x86_64 php-pecl-judy-devel.x86_64
 ln -s /opt/remi/php56/root/usr/bin/php-config /usr/bin/php-config
 ln -s /opt/remi/php56/root/usr/lib64/php/build /usr/lib64/php/build
```

**Comment by remicollet** [comment]
> had the same problem with remi repos for PHP 5.6 and Centos 6.5

As this extension is part of "remi" repository, you don't even have to build it, just install it with yum ;)
