### ISSUE TITLE
Usage clarification

### ISSUE THREAD

**Issue by remicollet** [arnaud-lb/php-memory-profiler#14]
From README.md, usage is extension=memprof.so
```
$ php -n -d extension=modules/memprof.so -v
PHP 7.0.15 (cli) (built: Jan 17 2017 16:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
But from code both zend_extension and zend_module_entry are present, so can also be loaded using zend_extension=memprof.so
```
$ php -n -d zend_extension=$PWD/modules/memprof.so -v
PHP 7.0.15 (cli) (built: Jan 17 2017 16:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with memprof v2.0.0, Copyright (c) 2013, by Arnaud Le Blanc
```

Please clarify usage (and perhaps, clean uneeded code)

**Comment by arnaud-lb** [comment]
Hi

Originally the extension required to be loaded as a zend extension, but this is not required anymore. The zend_extension is kept here for backwards compatibility, and the only thing it does is to load the php extension. This may be removed now, I guess.
