### ISSUE TITLE
What is the unit of measurement used for the consumed memory size?

### ISSUE THREAD

**Issue by kharbat** [arnaud-lb/php-memory-profiler#27]
Hello,

Just wanted to check since I couldn't find this info anywhere. 

What is the unit of measurement used for Memory Size cost. I'm using Kcachegrind, and it displays plane numbers no units, e.g bytes or kilobytes. 

Thanks

**Comment by arnaud-lb** [comment]
Hello @kharbat 

The memory usage is measured in bytes

**Comment by kharbat** [comment]
Thanks for the response,  just to double check are both attached screenshots measured in bytes?

![screenshot from 2019-02-04 11-59-45](https://user-images.githubusercontent.com/34914/52227485-48d95c80-2875-11e9-9509-5d3c6182afb2.png)
![screenshot from 2019-02-04 11-59-59](https://user-images.githubusercontent.com/34914/52227493-4bd44d00-2875-11e9-876f-14206df6853a.png)

**Comment by arnaud-lb** [comment]
Yes, but some are % as well :)
