### ISSUE TITLE
Is memprof safe to run on production sites?

### ISSUE THREAD

**Issue by kharbat** [arnaud-lb/php-memory-profiler#28]
Hello,

I know it's not an easy yes or no question, but i would like to run memprof on a production site to profile some parts of the code, as it's really hard to replicate all the details locally.  I just wanted to check if this is feasible, and if there's any potential side effects.

Server is LAPP Ubuntu 16, PHP 5.6

Thanks

**Comment by arnaud-lb** [comment]
Hello,

memprof has zero overhead until `memprof_enable()` is called, so it should be safe to install the extension in production.

Once `memprof_enable()` is called, the extension has a considerable overhead in memory allocations, though. Other than the extra memory usage, it's safe.
