### ISSUE TITLE
make fails on php 7.4.14

### ISSUE THREAD

**Issue by nachitox** [arnaud-lb/php-memory-profiler#46]
At least to me, when calling `make`, I get this:

> /root/php-memory-profiler/memprof.c: In function 'memprof_zend_execute_internal':
/root/php-memory-profiler/memprof.c:675:53: error: 'zend_pass_function' undeclared (first use in this function)
  if (&execute_data_ptr->func->internal_function == &zend_pass_function) {
                                                     ^
/root/php-memory-profiler/memprof.c:675:53: note: each undeclared identifier is reported only once for each function it appears in
Makefile:194: recipe for target 'memprof.lo' failed

**Comment by arnaud-lb** [comment]
Hi @nachitox

Could you copy the full configure and make output ?

**Comment by nachitox** [comment]
Not sure what changed, but it works now :/

**Comment by arnaud-lb** [comment]
Thank you. Closing the issue then :)
