### ISSUE TITLE
Installation MacOS

### ISSUE THREAD

**Issue by webrune** [arnaud-lb/php-memory-profiler#50]
Hi! How to install on MacOS?

appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/install/pear-build-alexanderspicinAQ3krS/memprof-3.0.0/libtool --mode=compile cc  -I. -I/private/tmp/pear/install/memprof -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-alexanderspicinAQ3krS/memprof-3.0.0/include -I/private/tmp/pear/install/pear-build-alexanderspicinAQ3krS/memprof-3.0.0/main -I/private/tmp/pear/install/memprof -I/Applications/MAMP/bin/php/php7.4.2/include/php -I/Applications/MAMP/bin/php/php7.4.2/include/php/main -I/Applications/MAMP/bin/php/php7.4.2/include/php/TSRM -I/Applications/MAMP/bin/php/php7.4.2/include/php/Zend -I/Applications/MAMP/bin/php/php7.4.2/include/php/ext -I/Applications/MAMP/bin/php/php7.4.2/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/install/memprof/memprof.c -o memprof.lo
mkdir .libs
 cc -I. -I/private/tmp/pear/install/memprof -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-alexanderspicinAQ3krS/memprof-3.0.0/include -I/private/tmp/pear/install/pear-build-alexanderspicinAQ3krS/memprof-3.0.0/main -I/private/tmp/pear/install/memprof -I/Applications/MAMP/bin/php/php7.4.2/include/php -I/Applications/MAMP/bin/php/php7.4.2/include/php/main -I/Applications/MAMP/bin/php/php7.4.2/include/php/TSRM -I/Applications/MAMP/bin/php/php7.4.2/include/php/Zend -I/Applications/MAMP/bin/php/php7.4.2/include/php/ext -I/Applications/MAMP/bin/php/php7.4.2/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/install/memprof/memprof.c  -fno-common -DPIC -o .libs/memprof.o
/private/tmp/pear/install/memprof/memprof.c:120:3: warning: No support for malloc hooks, this build will not track persistent allocations [-W#warnings]
#       warning No support for malloc hooks, this build will not track persistent allocations
        ^
/private/tmp/pear/install/memprof/memprof.c:762:74: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
        spprintf(&filename, 0, "%s%smemprof.%s.%ld", output_dir, slash, format, ts);
                                               ~~~                              ^~
                                               %lld
/private/tmp/pear/install/memprof/memprof.c:984:7: error: use of undeclared identifier 'HAVE_MALLOC_HOOKS'
                if (HAVE_MALLOC_HOOKS && strcmp(MEMPROF_FLAG_NATIVE, flag) == 0) {
                    ^
/private/tmp/pear/install/memprof/memprof.c:1199:66: error: use of undeclared identifier 'HAVE_MALLOC_HOOKS'
        php_info_print_table_header(2, "memprof native malloc support", HAVE_MALLOC_HOOKS ? "Yes" : "No");
                                                                        ^
2 warnings and 2 errors generated.
make: *** [memprof.lo] Error 1
ERROR: `make' failed

**Comment by arnaud-lb** [comment]
Hi @webrune 

I've pushed a fix on the v3 branch, does it fixes the problem for you ? You can install the v3 branch by doing this:

```
git clone github.com/arnaud-lb/php-memory-profiler
cd php-memory-profiler
git clean -dfx
phpize
./configure
make
sudo make install
```

**Comment by arnaud-lb** [comment]
Hi,

Thank you for this report. I've pushed a released on pecl: https://pecl.php.net/package/memprof
