### ISSUE TITLE
Release 3.0.1

### ISSUE THREAD

**Issue by glensc** [arnaud-lb/php-memory-profiler#52]
Please make 3.0.1 release, so this commit be available via pecl download:
- https://github.com/arnaud-lb/php-memory-profiler/commit/1ebb467186a7a4dcfc0df0bad2df3a944b9f9349#commitcomment-51719408

Fixes build on macOS:
- https://github.com/kabel/homebrew-pecl/pull/26#issuecomment-855000546

**Comment by glensc** [comment]
This would also fix this issue:
- https://github.com/arnaud-lb/php-memory-profiler/issues/50

**Comment by arnaud-lb** [comment]
Thank you @glensc

I've pushed a released on pecl: https://pecl.php.net/package/memprof
