### ISSUE TITLE
Strange text in calls: "(todo.php)"

### ISSUE THREAD

**Issue by Ziggizag** [arnaud-lb/php-memory-profiler#58]
You can see the QCacheGrind [screenshot](https://i.imgur.com/AxNZzaF.png).

Any idea - is it a bug or a feature?

**Comment by codedge** [comment]
I get the same. @Ziggizag did you figure it out why that happens?

**Comment by arnaud-lb** [comment]
Hi @Ziggizag @codedge 

The `todo.php` part is supposed to be a filename. IIRC it was required by the callgrind file format, but I didn't took the time to add the actual filename yet, so for now it's always `todo.php` :)

**Comment by maximal** [comment]
Seems like it’s not that complicated to add the filename:
https://github.com/arnaud-lb/php-memory-profiler/blob/v3/memprof.c#L1418

Does `php_stream` have info about its file path?
