### ISSUE TITLE
Missing a method to determine the memprof version

### ISSUE THREAD

**Issue by rgpublic** [arnaud-lb/php-memory-profiler#59]
Perhaps I missed sth. but how can I determine the memprof version (3.0.1) without parsing the "phpinfo()" output? A method like memprof_version() or sth. would be very nice...

**Comment by arnaud-lb** [comment]
Hi @rgpublic 

Added `memprof_version()` in #66

**Comment by rgpublic** [comment]
Cool. Very useful. Thank you!
