### ISSUE TITLE
Pecl install memprof install fails.

### ISSUE THREAD

**Issue by torressam333** [arnaud-lb/php-memory-profiler#67]
Issue: 

```
pecl install memprof
No releases for package "pecl/memprof" exist
install failed

```

Machine Specs

```
5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I installed the necessary dependency `apt install libjudy-dev` and then tried to install memprof using `pecl` and I got the above notice.

Is there an underlying issue with this package?

Thank you.

**Comment by arnaud-lb** [comment]
Hi @torressam333 

I have the same result when I forget to run pecl as root. Does `sudo pecl install memprof` work for you ?

**Comment by torressam333** [comment]
Hi @arnaud-lb I got the same issue even when running as root 

```
sudo pecl install memprof
No releases for package "pecl/memprof" exist
install failed

```

**Comment by torressam333** [comment]
@arnaud-lb  I guess I was on a limited network with security blockage...I was able to get it to work when switching to a hotspot.
Thank you.
