### ISSUE TITLE
Documentation change: mention Arch Linux package?

### ISSUE THREAD

**Issue by lkrms** [arnaud-lb/php-memory-profiler#73]
### Description

Hello

I've just added a [`php-memprof` package](https://aur.archlinux.org/packages/php-memprof/) to the Arch Linux user repository (AUR) and will be maintaining it moving forward.

Would you like this to be mentioned as an install option in the README? Happy to create a PR if so.

Thank you :)

**Comment by arnaud-lb** [comment]
Hi @lkrms 

Awesome! Sure, go ahead :)

**Comment by lkrms** [comment]
Sorry, I only just returned to this after updating the package to 3.0.2. Have opened a pull request now.

Hopefully I haven't ruined the vibe of the README :)
