### ISSUE TITLE
fatal error: sys/queue.h: No such file or directory

### ISSUE THREAD

**Issue by ramth05** [arnaud-lb/php-memory-profiler#96]
### Description

Getting below error while running **make**  ( **manual install** )

/bin/sh /app/php-memory-profiler/libtool --mode=compile cc -I. -I/app/php-memory-profiler -I/app/php-memory-profiler/include -I/app/php-memory-profiler/main -I/app/php-memory-profiler -I/usr/include/php81 -I/usr/include/php81/main -I/usr/include/php81/TSRM -I/usr/include/php81/Zend -I/usr/include/php81/ext -I/usr/include/php81/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -DZEND_COMPILE_DL_EXT=1 -c /app/php-memory-profiler/memprof.c -o memprof.lo  -MMD -MF memprof.dep -MT memprof.lo
mkdir .libs
 cc -I. -I/app/php-memory-profiler -I/app/php-memory-profiler/include -I/app/php-memory-profiler/main -I/app/php-memory-profiler -I/usr/include/php81 -I/usr/include/php81/main -I/usr/include/php81/TSRM -I/usr/include/php81/Zend -I/usr/include/php81/ext -I/usr/include/php81/ext/date/lib -DHAVE_CONFIG_H -g -O2 -DZEND_COMPILE_DL_EXT=1 -c /app/php-memory-profiler/memprof.c -MMD -MF memprof.dep -MT memprof.lo  -fPIC -DPIC -o .libs/memprof.o
/app/php-memory-profiler/memprof.c:27:10: fatal error: sys/queue.h: No such file or directory
   27 | #include <sys/queue.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

### php-memprof Version

Latest master commit

### PHP Version

PHP 8.1.17

### Operating System

Alpine Linux v3.16

**Comment by JeroenBoesten** [comment]
For me the solution in this issue fixed it for me: https://github.com/arnaud-lb/php-memory-profiler/issues/15

**Comment by arnaud-lb** [comment]
Thank you @JeroenBoesten. I've updated the README to add `bsd-compat-headers` in dependencies.
